name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import mlflow; print('MLflow:', mlflow.__version__)"

      - name: Cache DVC cache
        uses: actions/cache@v4
        with:
          path: .dvc/cache
          key: dvc-cache-${{ hashFiles('dvc.lock') }}
          restore-keys: |
            dvc-cache-

      - name: Run DVC pipeline
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          # optional. if you use this in code, keep it here
          MLFLOW_TRACKING_URI: https://dagshub.com/jimit-code/mlops-mini-project.mlflow
        run: |
          dvc repro

      - name: Run unit tests
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_URI: https://dagshub.com/jimit-code/mlops-mini-project.mlflow
        run: |
          python -m unittest tests.test_model

      - name: Promote MLflow model
        if: success()
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_URI: https://dagshub.com/jimit-code/mlops-mini-project.mlflow
        run: |
          python src/models/promote_model.py

      - name: configure AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Login to Amazon EC2
        if: success() && github.event_name == 'push'
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image  to ECR
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: | 
            ${{ steps.ecr.outputs.registry }}/ecr_practice:latest
            ${{ steps.ecr.outputs.registry }}/ecr_practice:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ steps.ecr.outputs.registry }}
            docker pull ${{ steps.ecr.outputs.registry }}/ecr_practice:${{ github.sha }}
            docker rm -f my-app || true
            docker run -d --restart unless-stopped -p 80:5000 --name my-app \
              -e DAGSHUB_USERNAME=${{ secrets.DAGSHUB_USERNAME }} \
              -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} \
              -e MLFLOW_TRACKING_URI=https://dagshub.com/jimit-code/mlops-mini-project.mlflow \
              ${{ steps.ecr.outputs.registry }}/ecr_practice:${{ github.sha }}
            docker ps --filter "name=my-app"