name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import mlflow; print('MLflow:', mlflow.__version__)"

      - name: Cache DVC cache
        uses: actions/cache@v4
        with:
          path: .dvc/cache
          key: dvc-cache-${{ hashFiles('dvc.lock') }}
          restore-keys: |
            dvc-cache-

      - name: Run DVC pipeline
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          # optional. if you use this in code, keep it here
          MLFLOW_TRACKING_URI: https://dagshub.com/jimit-code/mlops-mini-project.mlflow
        run: |
          dvc repro

      - name: Run unit tests
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_URI: https://dagshub.com/jimit-code/mlops-mini-project.mlflow
        run: |
          python -m unittest tests.test_model

      - name: Promote MLflow model
        if: success()
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
          MLFLOW_TRACKING_URI: https://dagshub.com/jimit-code/mlops-mini-project.mlflow
        run: |
          python src/models/promote_model.py

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/emotion:latest
      
      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/emotion:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -p 80:5000 --name my-app \
              -e MLFLOW_TRACKING_URI="https://dagshub.com/jimit-code/mlops-mini-project.mlflow" \
              ${{ secrets.DOCKER_HUB_USERNAME }}/emotion:latest
            docker ps --filter "name=my-app"